#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_N60Pro

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout
      uses: actions/checkout@master

    - name: Check disk space
      run: |
        df . -h

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/gw826943555/openwrt
        REPO_BRANCH: main
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt

        # 添加feeds
        git clone --recurse-submodules https://github.com/gw826943555/openwrt-packages-misc package/misc

        git clone https://github.com/muink/openwrt-chinadns-ng package/chinadns-ng
        git clone https://github.com/immortalwrt/homeproxy package/luci-app-homeproxy
        git clone https://github.com/yichya/luci-app-xray package/luci-app-xray
        
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configuration Customization - Build_N60Pro
      env:
        CONFIG_FILE: 'n60pro.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
    
    - name: Cache Build
      uses: klever1988/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: 'mediatek'
        prefix: 'openwrt'

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin/targets/*
        
    - name: Generate release tag
      id: release_tag
      run: |
        echo "release_tag=OpenWrt-n60pro-$(date +"%Y.%m.%d-%H%M")">> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.release_tag.outputs.release_tag }}
        files: |
          openwrt/bin/targets/*/*/openwrt-*
